on:
  push:
    branches: [ main ]
  name: Deploy website on push 
# jobs:
#   web-deploy:
#       name: Auto Deploy
#       runs-on: ubuntu-latest
#       steps:
#       - name: Get latest code
#       uses: actions/checkout@v2.3.2

#       - name: Rsync Deployments Action
#   # You may pin to the exact commit or the version.
#   # uses: Burnett01/rsync-deployments@796cf0d5e4b535745ce49d7429f77cf39e25ef39
#   uses: Burnett01/rsync-deployments@7.0.1
#   with:
#     # The switches
#     switches: -avzr --delete
#     # The remote path
#     remote_path: /var/www/html/doc/
#     # The remote host
#     remote_host: 34.143.255.60
#     # The remote user
#     remote_user: asus
#     # The remote key
#     remote_key: ${{secrets.DEPLOY_KEY}}

          
