on:
  push:
    branches: [ main ]
name: Deploy website on push
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Sync files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /var/www/html/doc/
        remote_host: 34.143.255.60
        remote_user: asus
        remote_key: ${{ secrets.DEPLOY_KEY }}
