on:
  push:
    branches: [ main ]
name: Deploy website on push 
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
    uses: actions/checkout@v2.3.2
